[package]
name = "rust_04b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
time = "*"
itertools = "*"
scan_fmt = "*"
regex = "*"